# This is a basic workflow to help you get started with Actions

name: Terraform Alicloud Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform_deploy:
    name: 'Terraform Deploy to Alicloud'
    runs-on: ubuntu-latest
    # Define default working directory for steps that use terraform
    
    # Define environment variables for the entire job
    env:
      ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
      ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY }}
      # Specify your Alibaba Cloud region if not set in provider block
      ALICLOUD_REGION: "${{ vars.ALICLOUD_REGION }}"

      # --- 新增：Terraform 输入变量 ---
      # 从 Variables 获取资源前缀
      TF_VAR_resource_prefix: ${{ vars.TF_VAR_resource_prefix }} # 例如: sintan1071-test

      # 从 Secrets 获取密码
      TF_VAR_rds_password: ${{ secrets.TF_VAR_rds_password }}
      TF_VAR_k8s_node_password: ${{ secrets.TF_VAR_k8s_node_password }}
      TF_VAR_redis_password: ${{ secrets.TF_VAR_redis_password }}
      # --- 环境变量添加结束 ---

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Installs the specific version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6 # Specify your desired Terraform version

      # Initialize a new or existing Terraform working directory
      # by creating initial files, loading any remote state, and downloading modules.
      - name: Terraform Init
        id: init
        run: terraform init
        # Env vars now defined at job level

      # Generates an execution plan for Terraform
      # This step is optional but highly recommended to review changes before applying
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=alicloud.tfplan
        # Env vars now defined at job level

      # On push to main branch or manual dispatch, automatically apply the Terraform plan
      # Use -auto-approve to skip interactive approval
      - name: Terraform Apply
        # Only run apply on push to main or workflow_dispatch
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' 
        run: terraform apply -auto-approve "alicloud.tfplan"
        # Env vars now defined at job level
